# Generated by Django 5.1.4 on 2024-12-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('lecturer', 'Lecturer')], default=None, max_length=10, null=True),
        ),
    ]
