# Generated by Django 5.1.3 on 2024-12-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('students', 'Student'), ('lecturers', 'Lecturer')], max_length=10, null=True),
        ),
    ]
