# Generated by Django 5.1.4 on 2024-12-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_course_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.CharField(max_length=190),
        ),
    ]
